apiVersion: v1
appVersion: "0.1"
description: NF Service template.
engine: gotpl
maintainers:
- email: maintainer@xgvela.org
  name: xGVela Maintainer
name: xgvela
tillerVersion: '>=2.8.0'
version: "cnf_mgmt_tag"
